blank_issues_enabled: false
contact_links:
    - name: Bioconductor Support Site
      url: https://support.bioconductor.org/tag/curatedMetagenomicData/
      about: Please ask and answer questions here.
