name: Update combined_metadata.rda

on:
  schedule:
    - cron: "0 5 * * 6"

jobs:
  build_combined_metadata:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:

    - name: Checkout curatedMetagenomicData
      uses: actions/checkout@v2

    - name: Install curatedMetagenomicDataCuration
      run: |
        install.packages("remotes")
        remotes::install_github("waldronlab/omicidxClientR")
        remotes::install_github("waldronlab/curatedMetagenomicDataCuration")
      shell: Rscript {0}

    - name: Generate combined_metadata.rda
      id: generate_metadata
      run: |
        library("curatedMetagenomicDataCuration")
        message(paste("****", Sys.time(), "Make combined metadata ****"))
        combined_metadata <-
            curatedMetagenomicDataCuration:::makeCombinedMetadata()
        path <- paste(Sys.getenv("GITHUB_WORKSPACE"),
                      "data/combined_metadata.rda",
                      sep = "/")
        save(combined_metadata, file = path, compression_level = 9)
        message(paste("\n****", Sys.time(), "Check curation ****"))
        status <- "passing"
        tryCatch(curatedMetagenomicDataCuration::checkCuration(combined_metadata),
             warning = function(w) {
                 status <<- "failing"
                 message("**** Setting status to", status, "****")
                 message(paste(w, "\n"))
        })
        # Save status and color for badge in file for next step
        color = if (status == "passing") "brightgreen" else "red"
        message(paste("::set-output name=status::", status, sep=""))
        message(paste("::set-output name=color::", color, sep=""))
      shell: Rscript {0}

    - name: Get actions URL
      id: actions_url
      run: echo "::set-output name=url::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

    - name: Test combined_metadata.rda
      run: |
        install.packages("testthat")
        testthat::test_file("tests/testthat/test-combined_metadata.R")
      shell: Rscript {0}

    - name: Commit and create pull request for updated combined_metadata.rda
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update data/combined_metdata.rda
        committer: GitHub Actions <noreply@github.com>
        signoff: false
        branch: update-combined-metadata
        delete-branch: true
        title: 'Update combined_metadata.rda'
        body: |
          Update combined_metadata.rda.

          [![Curation Status](https://img.shields.io/badge/Curation-${{ steps.generate_metadata.outputs.status }}-${{ steps.generate_metadata.outputs.color }})](${{ steps.actions_url.outputs.url }})

          Auto-generated by [create-pull-request][1].

          [1]: https://github.com/peter-evans/create-pull-request
        labels: automated pr
        team-reviewers: |
          owners
          maintainers
        draft: false
