name: Update combined_metadata.rda

on:
  schedule:
    - cron: "0 5 * * 6"

jobs:
  build_combined_metadata:
    runs-on: ubuntu-latest
    steps:
    - name: Install system dependencies
      run: sudo apt-get -y install libcurl4-openssl-dev

    - name: Set up R
      uses: r-lib/actions/setup-r@v1

    - name: Install remotes and curatedMetagenomicDataCuration
      run: |
        install.packages("remotes")
        remotes::install_github("waldronlab/curatedMetagenomicDataCuration")
      shell: Rscript {0}

    - name: Checkout curatedMetagenomicData
      uses: actions/checkout@v2

    - name: Generate combined_metadata.rda
      run: |
        library("dplyr")
        library("data.table")
        library("curatedMetagenomicDataCuration")
        combined_metadata <- curatedMetagenomicDataCuration:::makeCombinedMetadata()
        path <- paste(Sys.getenv("GITHUB_WORKSPACE"),
                      "data/combined_metadata.rda",
                      sep = "/")
        save(combined_metadata, file = path, compression_level = 9)
      shell: Rscript {0}

    - name: Test combined_metadata
      run: |
        install.packages("testthat")
        testthat::test_file("tests/testthat/test-combined_metadata.R")
      shell: Rscript {0}

    - name: Commit and create pull request for updated combined_metadata.rda
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update data/combined_metdata.rda
        committer: GitHub Actions <noreply@github.com>
        signoff: false
        branch: update-combined-metadata
        delete-branch: true
        title: 'Update combined_metadata.rda'
        body: |
          Update combined_metadata.rda.
          Auto-generated by [create-pull-request][1].

          [1]: https://github.com/peter-evans/create-pull-request
        labels: automated pr
        team-reviewers: |
          owners
          maintainers
        draft: false
